apiVersion: v1
kind: Service
metadata:
  name: hbase
spec:
  selector:
    name: hbase
  clusterIP: None
  ports:
    - name: zookeeper
      port: 2181
      targetPort: 2181
    - name: master
      port: 60000
      targetPort: 60000
    - name: master-ui
      port: 60010
      targetPort: 60010
    - name: regionserver
      port: 60020
      targetPort: 60020
    - name: regionserver-ui
      port: 60030
      targetPort: 60030
---

apiVersion: v1
kind: Pod
metadata:
  name: hbase
  labels:
    name: hbase
spec:
  containers:
    - image: gaborgsomogyi/hbase:latest
      imagePullPolicy: Never
      name: hbase
      volumeMounts:
        - mountPath: /share
          name: volume
  volumes:
    - name: volume
      hostPath:
        path: /share
        type: Directory
